In [1]:
from google.colab import files
uploaded = files.upload()

Saving loan_approval_data.csv to loan_approval_data.csv


In [2]:
import pandas as pd
df = pd.read_csv('loan_approval_data.csv')
df.drop(columns=["customer_id"], inplace=True)
df = pd.get_dummies(df, columns=["occupation_status", "product_type", "loan_intent"], dtype=int)
print(df.shape)
df.head(20)



(50000, 28)


age  years_employed  annual_income  credit_score  credit_history_years  \
0    40            17.2          25579           692                   5.3   
1    33             7.3          43087           627                   3.5   
2    42             1.1          20840           689                   8.4   
3    53             0.5          29147           692                   9.8   
4    32            12.5          63657           630                   7.2   
5    32            13.4          32015           570                   7.3   
6    53            22.9          44989           674                  11.1   
7    44             4.2          80603           625                  18.5   
8    29             5.9          28416           569                   2.6   
9    41             7.0          70717           638                  21.5   
10   29             5.0          15000           657                   8.9   
11   29             1.3          17029           668                   4.3   
12   37             1.3          49084           580                  11.3   
13   18             0.0          55958           681                   1.4   
14   18             1.0          99020           561                   1.6   
15   28             0.4          59609           654                   2.6   
16   22             1.0          82604           605                   3.5   
17   38             5.3          53356           671                  19.8   
18   24             5.4          18675           531                   3.3   
19   18             1.0          55309           597                   1.5   

    savings_assets  current_debt  defaults_on_file  delinquencies_last_2yrs  \
0              895         10820                 0                        0   
1              169         16550                 0                        1   
2               17          7852                 0                        0   
3             1480         11603                 0                        1   
4              209         12424                 0                        0   
5              253          1120                 0                        0   
6            19667         19298                 0                        0   
7              830         38382                 0                        0   
8             1334         22668                 1                        2   
9             1578         21394                 0                        1   
10            2105          3866                 0                        0   
11             215          5592                 0                        0   
12            1289         21106                 0                        0   
13             378         14090                 0                        0   
14             538         13733                 0                        1   
15             881          9183                 0                        0   
16            9216         16116                 0                        0   
17            6339         23085                 0                        1   
18              11          3280                 0                        2   
19             346          2930                 0                        0   

    derogatory_marks  ...  occupation_status_Student  \
0                  0  ...                          0   
1                  0  ...                          0   
2                  0  ...                          1   
3                  0  ...                          1   
4                  0  ...                          0   
5                  2  ...                          0   
6                  0  ...                          0   
7                  0  ...                          0   
8                  0  ...                          0   
9                  0  ...                          0   
10                 0  ...                          0   
11                 0  ...        

In [3]:
from sklearn.model_selection import train_test_split

X = df.drop(columns=["loan_status"])
y = df["loan_status"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report


In [6]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [7]:
y_pred = model.predict(X_test)


In [8]:
print("Accuracy:", accuracy_score(y_test, y_pred))

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

print(classification_report(y_test, y_pred))

Accuracy: 0.8709
Confusion Matrix:
 [[3840  669]
 [ 622 4869]]
              precision    recall  f1-score   support

           0       0.86      0.85      0.86      4509
           1       0.88      0.89      0.88      5491

    accuracy                           0.87     10000
   macro avg       0.87      0.87      0.87     10000
weighted avg       0.87      0.87      0.87     10000



In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

lr_model = LinearRegression()
lr_model.fit(X_train, y_train)

y_pred = lr_model.predict(X_test)

print("MSE:", mean_squared_error(y_test, y_pred))
print("R2 score:", r2_score(y_test, y_pred))

MSE: 0.11655100614631687
R2 score: 0.5292564826989543


In [10]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

svm_model = SVC(kernel="rbf", random_state=42)
svm_model.fit(X_train, y_train)

y_pred_svm = svm_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_svm))
print(confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

Accuracy: 0.9104
[[4030  479]
 [ 417 5074]]
              precision    recall  f1-score   support

           0       0.91      0.89      0.90      4509
           1       0.91      0.92      0.92      5491

    accuracy                           0.91     10000
   macro avg       0.91      0.91      0.91     10000
weighted avg       0.91      0.91      0.91     10000



In [11]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train, y_train)

y_pred_knn = knn_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_knn))
print(confusion_matrix(y_test, y_pred_knn))
print(classification_report(y_test, y_pred_knn))

Accuracy: 0.8592
[[3604  905]
 [ 503 4988]]
              precision    recall  f1-score   support

           0       0.88      0.80      0.84      4509
           1       0.85      0.91      0.88      5491

    accuracy                           0.86     10000
   macro avg       0.86      0.85      0.86     10000
weighted avg       0.86      0.86      0.86     10000



In [12]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, y_train)

y_pred_dt = dt_model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print(confusion_matrix(y_test, y_pred_dt))
print(classification_report(y_test, y_pred_dt))

Accuracy: 0.8796
[[3905  604]
 [ 600 4891]]
              precision    recall  f1-score   support

           0       0.87      0.87      0.87      4509
           1       0.89      0.89      0.89      5491

    accuracy                           0.88     10000
   macro avg       0.88      0.88      0.88     10000
weighted avg       0.88      0.88      0.88     10000



In [17]:
import torch
from torch.nn import Linear, Dropout
from torch.nn.modules.activation import Softmax, ReLU
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from torchsummary import summary

input_shape = 27

model = torch.nn.Sequential(
    Linear(27, 128),
    ReLU(),
    Dropout(0.2),

    Linear(128, 64),
    ReLU(),
    Dropout(0.2),

    Linear(64, 2)
)

from torchvision import datasets, transforms
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset
import torch
from torch.utils.data import TensorDataset, DataLoader

X_train_t = torch.tensor(X_train, dtype=torch.float32)
y_train_t = torch.tensor(y_train.values, dtype=torch.long)

X_test_t = torch.tensor(X_test, dtype=torch.float32)
y_test_t  = torch.tensor(y_test.values, dtype=torch.long)

train_dataset = TensorDataset(X_train_t, y_train_t)
test_dataset  = TensorDataset(X_test_t, y_test_t)

train_loader = DataLoader(train_dataset, batch_size=128, shuffle=True)
test_loader  = DataLoader(test_dataset, batch_size=128)

criterion = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

epochs = 20

for epoch in range(epochs):
    model.train()
    total_loss = 0
    for batch, labels in train_loader:
      outputs = model(batch)
      loss = criterion(outputs, labels)

      optimizer.zero_grad()
      loss.backward()
      optimizer.step()

      total_loss += loss.item()

    print(f"Epoch {epoch+1}: loss = {total_loss/len(train_loader):.4f}")

Epoch 1: loss = 0.3127
Epoch 2: loss = 0.2415
Epoch 3: loss = 0.2295
Epoch 4: loss = 0.2244
Epoch 5: loss = 0.2173
Epoch 6: loss = 0.2151
Epoch 7: loss = 0.2120
Epoch 8: loss = 0.2091
Epoch 9: loss = 0.2083
Epoch 10: loss = 0.2061
Epoch 11: loss = 0.2031
Epoch 12: loss = 0.2034
Epoch 13: loss = 0.2012
Epoch 14: loss = 0.2004
Epoch 15: loss = 0.1982
Epoch 16: loss = 0.1977
Epoch 17: loss = 0.1964
Epoch 18: loss = 0.1949
Epoch 19: loss = 0.1932
Epoch 20: loss = 0.1923


In [18]:
model.eval()
correct = 0
total = 0

with torch.no_grad():
    for batch, labels in test_loader:
        outputs = model(batch)
        preds = outputs.argmax(dim=1)

        correct += (preds == labels).sum().item()
        total += labels.size(0)

print(f"Accuracy: {100 * correct / total:.2f}%")

Accuracy: 91.29%
